print("Donne moi une note d'évaluation sur 20")
moyenne=float(input())
print("Donne moi une deuxième note d'évaluation sur 20")
moyenne=float(moyenne)+float(input())
print("Donne moi une troisième note d'évaluation sur 20")
moyenne=float(moyenne)+float(input())
print("Donne moi une quatrième note d'évaluation sur 20")
moyenne=float(moyenne)+float(input())
print("Donne moi une cinqième note d'évaluation sur 20")
moyenne=float(moyenne)+float(input())
print("La moyenne des notes est "+ str(moyenne/5) +"/20")